services:
  db:
    container_name: spring-db-container
    build:
      context: .
      dockerfile: images/Dockerfile.db
    image: spring-db-image
    ports:
      - "3307:3306"
    networks:
      - spring-app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest1234" ]
      interval: 5s
      timeout: 5s
      retries: 100

  app:
    container_name: spring-app-container
    build:
      context: .
      dockerfile: images/Dockerfile.be
    image: spring-app-image
    ports:
      - "8080:8080"
    networks:
      - spring-app-network
    depends_on:
      db:
        condition: service_healthy

networks:
  spring-app-network: