services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: backend-db
    volumes:
      - ./db-scripts/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "backend_app", "-ptest1234" ]
      interval: 5s
      timeout: 5s
      retries: 100
    ports:
    - ${DB_PORT}:3306
    networks:
    - spring


  backend:
    container_name: backend-spring
    build:
      context: .
      dockerfile: Dockerfile.spring
    networks:
      - spring
    env_file:
        - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"


networks:
  spring:





