services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: backend-db
    volumes:
      - ./db-scripts/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=test1234

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "backend_app", "-ptest1234" ]
      interval: 5s
      timeout: 5s
      retries: 100
    ports:
    - "3308:3306"
    networks:
    - spring

  backend:
    container_name: backend-spring
    build:
      context: .
      dockerfile: Dockerfile.spring
    networks:
      spring:
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_ROLE: ${DB_ROLE}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"


networks:
  spring:





