spring.application.name=java-backend-1-group
spring.datasource.url=jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_SCHEMA}
spring.datasource.hikari.username=${DB_USERNAME}
spring.datasource.hikari.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
